### ISSUE TITLE
[CORREÇÃO] Erro na hora do update de usuários

### ISSUE THREAD

**Issue by CopaDoMorro** [yohangreg/back_copa_do_morro#1]
**Descrição:**
Quando atualizo o usuário via api, o end point informa um erro de e-mail já cadastrado

**Passos para Reproduzir:**

N/A

**Comportamento Esperado:**

Atualizar o usuário em questão no bando de dados

**Comportamento Observado:**

Erro informando que usuário já existe

**Informações Adicionais:**

N/A

**Ambiente:**

N/A

**Screenshots:**

N/A

**Prioridade:** [Alta/Média/Baixa]

**Comment by yohangreg** [comment]
Feito.
